Remove uses of reduce/spread which causes significant latency to large middlewares
dimatill/graphql-middleware pull request #567
Opened 2023-06-15 22:58 UTC by ryanquinn3

Hi there, at work we have a very large graphql schema and use graphql middlewares heavily. I've recently been debugging why our graphql server takes so long to start up and identified one area in this library that contributes a good chunk of that time. 

I found that this library performs quite poorly when a particular middleware contains a lot (~1k+) of keys. After a deeper inspection, I see that applicator.ts uses the [reduce/spread anti-pattern](https://prateeksurana.me/blog/why-using-object-spread-with-reduce-bad-idea/) which I have been bitten by a few times in the last handful of years. The simple changes in this PR should not change the behavior of this library at all but they did reduce the total latency of our `applyMiddleware` call from ~11s to about 6s. If others in the community are using this library with large schemas & middlewares then I want them to benefit as well.

2023-07-06 16:42 UTC, ryanquinn3 commented
Hey @dimatill, any chance you've had a moment to look over this change?

2023-07-07 16:04 UTC, dimatill commented
wow, @ryanquinn3 this is a great finding! Thank you!

2023-07-07 16:09 UTC, dimatill requested changes

2023-07-07 16:09 UTC, dimatill commented on src/applicator.ts
> +        );
please add the return statement

2023-07-07 16:09 UTC, dimatill commented on src/applicator.ts
> +        );
`Cannot find name 'field'`. Could you please rename `fieldName` back to `field`, or use `fieldName` inside the function?

2023-07-07 16:15 UTC, ryanquinn3 commented
@dimatill This is what I get for submitting the PR via github's web editor 😞 

Commit pushed. I've confirmed that the package builds & tests pass.

2023-07-07 16:18 UTC, merged

2023-07-07 16:18 UTC, dimatill commented
Thank you @ryanquinn3 !!!